/**
 * Generate road-snapped route polylines into src/data/routePaths.ts using the
 * public OSRM routing API. Run with:
 *
 *   npm run paths
 *
 * Requires Node 22.6+ (executed via --experimental-strip-types). No build step
 * — the output is plain data consumed by the simulation.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { CITIES } from "../src/data/cities.ts";
import type { LatLng } from "../src/lib/types.ts";

const OSRM = "https://router.project-osrm.org/route/v1/driving";
const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, "../src/data/routePaths.ts");

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function snap(stops: LatLng[]): Promise<LatLng[] | null> {
  // OSRM wants lng,lat;lng,lat order.
  const coords = stops.map(([lat, lng]) => `${lng},${lat}`).join(";");
  const url = `${OSRM}/${coords}?overview=full&geometries=geojson&continue_straight=true`;
  try {
    const res = await fetch(url);
    if (!res.ok) {
      console.warn(`  ! HTTP ${res.status}`);
      return null;
    }
    const data = (await res.json()) as {
      code: string;
      routes?: { geometry: { coordinates: [number, number][] } }[];
    };
    if (data.code !== "Ok" || !data.routes?.length) {
      console.warn(`  ! OSRM code=${data.code}`);
      return null;
    }
    // geojson coords are [lng, lat]; flip to our [lat, lng].
    return data.routes[0].geometry.coordinates.map(([lng, lat]) => [lat, lng]);
  } catch (err) {
    console.warn(`  ! ${(err as Error).message}`);
    return null;
  }
}

async function main() {
  const out: Record<string, LatLng[]> = {};

  for (const city of CITIES) {
    const byId = new Map(city.stops.map((s) => [s.id, s]));
    for (const route of city.routes) {
      const stopPos = route.stops.map((id) => byId.get(id)!.pos);
      process.stdout.write(`${city.name} ${route.number} … `);
      const path = await snap(stopPos);
      if (path) {
        out[route.id] = path.map(([a, b]) => [
          Math.round(a * 1e5) / 1e5,
          Math.round(b * 1e5) / 1e5,
        ]);
        console.log(`${path.length} pts`);
      } else {
        console.log("skipped (will use straight lines)");
      }
      await sleep(400); // be gentle with the public demo server
    }
  }

  const body = `import type { LatLng } from "@/lib/types";

/**
 * Road-snapped polylines per route id, generated by \`scripts/fetch-paths.ts\`
 * from the public OSRM routing API. When a route id is absent here, the
 * simulation falls back to straight lines between stops.
 *
 * DO NOT edit by hand — re-run \`npm run paths\` to regenerate.
 */
export const ROUTE_PATHS: Record<string, LatLng[]> = ${JSON.stringify(out)};
`;

  writeFileSync(OUT, body);
  console.log(`\nWrote ${Object.keys(out).length} routes → ${OUT}`);
}

main();
